import type {
  User,
  KnowledgeComponent,
  Problem,
  Submission,
  UserStats,
  Achievement,
  StudentProgress,
  ClassAnalytics,
} from "./types"

export const mockUser: User = {
  id: "1",
  name: "Sarah Chen",
  email: "sarah@example.com",
  role: "student",
  avatar: "/student-avatar.png",
  createdAt: "2023-10-15",
  bio: "Computer Science student passionate about algorithms and problem solving",
  location: "San Francisco, CA",
  githubUrl: "https://github.com/sarahchen",
  linkedinUrl: "https://linkedin.com/in/sarahchen",
}

export const mockKnowledgeComponents: KnowledgeComponent[] = [
  { id: "1", name: "For Loops", mastery: 85, problemsSolved: 24, lastPracticed: "2024-01-15" },
  { id: "2", name: "Arrays", mastery: 62, problemsSolved: 18, lastPracticed: "2024-01-14" },
  { id: "3", name: "Recursion", mastery: 45, problemsSolved: 12, lastPracticed: "2024-01-10" },
  { id: "4", name: "Functions", mastery: 78, problemsSolved: 22, lastPracticed: "2024-01-15" },
  { id: "5", name: "Conditionals", mastery: 92, problemsSolved: 28, lastPracticed: "2024-01-15" },
  { id: "6", name: "Strings", mastery: 58, problemsSolved: 15, lastPracticed: "2024-01-12" },
  { id: "7", name: "Sorting", mastery: 40, problemsSolved: 8, lastPracticed: "2024-01-08" },
  { id: "8", name: "OOP Basics", mastery: 33, problemsSolved: 6, lastPracticed: "2024-01-05" },
]

export const mockProblems: Problem[] = [
  {
    id: "1",
    title: "Two Sum",
    difficulty: "easy",
    topics: ["Array", "Hash Table"],
    knowledgeComponents: ["Arrays", "For Loops"],
    acceptanceRate: 48.5,
    totalSubmissions: 12345,
    description:
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
    inputFormat:
      "First line: integer n (array length)\nSecond line: n space-separated integers\nThird line: target integer",
    outputFormat: "Two space-separated integers representing the indices",
    constraints: ["2 ≤ n ≤ 10^4", "-10^9 ≤ nums[i] ≤ 10^9", "-10^9 ≤ target ≤ 10^9"],
    examples: [
      {
        input: "4\n2 7 11 15\n9",
        output: "0 1",
        explanation: "nums[0] + nums[1] = 2 + 7 = 9",
        isHidden: false,
        points: 10,
      },
      { input: "3\n3 2 4\n6", output: "1 2", isHidden: false, points: 10 },
    ],
    timeLimit: 5,
    memoryLimit: 256,
    source: "LeetCode #1",
  },
  {
    id: "2",
    title: "Reverse String",
    difficulty: "easy",
    topics: ["String", "Two Pointers"],
    knowledgeComponents: ["Strings", "For Loops"],
    acceptanceRate: 76.2,
    totalSubmissions: 8934,
    description: "Write a function that reverses a string. The input string is given as an array of characters.",
    inputFormat: "A string of characters",
    outputFormat: "The reversed string",
    constraints: ["1 ≤ s.length ≤ 10^5"],
    examples: [
      { input: "hello", output: "olleh", isHidden: false, points: 10 },
      { input: "world", output: "dlrow", isHidden: false, points: 10 },
    ],
    timeLimit: 5,
    memoryLimit: 256,
  },
  {
    id: "3",
    title: "Binary Tree Inorder Traversal",
    difficulty: "medium",
    topics: ["Tree", "Recursion", "Stack"],
    knowledgeComponents: ["Recursion", "OOP Basics"],
    acceptanceRate: 67.8,
    totalSubmissions: 5621,
    description: "Given the root of a binary tree, return the inorder traversal of its nodes' values.",
    inputFormat: "Binary tree in level-order format",
    outputFormat: "Space-separated integers representing inorder traversal",
    constraints: ["0 ≤ number of nodes ≤ 100", "-100 ≤ Node.val ≤ 100"],
    examples: [{ input: "[1,null,2,3]", output: "1 3 2", isHidden: false, points: 15 }],
    timeLimit: 5,
    memoryLimit: 256,
    source: "LeetCode #94",
  },
]

export const mockSubmissions: Submission[] = [
  {
    id: "1",
    userId: "1",
    problemId: "1",
    code: "def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        if target - num in seen:\n            return [seen[target - num], i]\n        seen[num] = i",
    language: "python",
    status: "accepted",
    testCasesPassed: 10,
    totalTestCases: 10,
    runtime: 0.123,
    memory: 2048,
    submittedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "2",
    userId: "1",
    problemId: "2",
    code: "def reverse_string(s):\n    return s[::-1]",
    language: "python",
    status: "accepted",
    testCasesPassed: 8,
    totalTestCases: 8,
    runtime: 0.045,
    memory: 1024,
    submittedAt: "2024-01-15T10:15:00Z",
  },
  {
    id: "3",
    userId: "1",
    problemId: "3",
    code: "class Solution:\n    def inorderTraversal(self, root):\n        result = []\n        self.helper(root, result)\n        return result\n    \n    def helper(self, node, result):\n        if not node:\n            return\n        self.helper(node.left, result)\n        result.append(node.val)\n        self.helper(node.right, result)",
    language: "python",
    status: "wrong_answer",
    testCasesPassed: 7,
    totalTestCases: 10,
    submittedAt: "2024-01-14T16:45:00Z",
  },
]

export const mockUserStats: UserStats = {
  problemsSolved: 47,
  totalProblems: 150,
  successRate: 78,
  currentStreak: 12,
  longestStreak: 23,
  rank: 23,
  totalStudents: 156,
  easyProblems: 25,
  mediumProblems: 18,
  hardProblems: 4,
}

export const mockAchievements: Achievement[] = [
  {
    id: "1",
    name: "First Steps",
    description: "Solved your first problem",
    icon: "🎯",
    unlocked: true,
    unlockedAt: "2023-10-16",
    rarity: "common",
  },
  {
    id: "2",
    name: "Week Warrior",
    description: "Maintained a 7-day streak",
    icon: "🔥",
    unlocked: true,
    unlockedAt: "2023-11-02",
    rarity: "rare",
  },
  {
    id: "3",
    name: "Array Master",
    description: "Solved 20 array problems",
    icon: "📊",
    unlocked: true,
    unlockedAt: "2023-12-15",
    rarity: "rare",
  },
  {
    id: "4",
    name: "Speed Demon",
    description: "Solved a problem in under 5 minutes",
    icon: "⚡",
    unlocked: true,
    unlockedAt: "2024-01-10",
    rarity: "epic",
  },
  {
    id: "5",
    name: "Problem Solver",
    description: "Solve 50 problems",
    icon: "🏆",
    unlocked: false,
    progress: 47,
    total: 50,
    rarity: "epic",
  },
  {
    id: "6",
    name: "Century Club",
    description: "Solve 100 problems",
    icon: "💯",
    unlocked: false,
    progress: 47,
    total: 100,
    rarity: "legendary",
  },
]

export const mockStudentProgress: StudentProgress[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    avatar: "/student-avatar.png",
    problemsSolved: 47,
    successRate: 78,
    lastActive: "2024-01-15T14:30:00Z",
    averageAttempts: 2.3,
    weakAreas: ["Recursion", "Sorting"],
    isAtRisk: false,
  },
  {
    id: "2",
    name: "Michael Johnson",
    email: "michael@example.com",
    avatar: "/student-avatar.png",
    problemsSolved: 23,
    successRate: 45,
    lastActive: "2024-01-10T09:15:00Z",
    averageAttempts: 4.8,
    weakAreas: ["Arrays", "Recursion", "OOP Basics"],
    isAtRisk: true,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily@example.com",
    avatar: "/student-avatar.png",
    problemsSolved: 62,
    successRate: 85,
    lastActive: "2024-01-15T16:45:00Z",
    averageAttempts: 1.8,
    weakAreas: ["Sorting"],
    isAtRisk: false,
  },
  {
    id: "4",
    name: "David Kim",
    email: "david@example.com",
    avatar: "/student-avatar.png",
    problemsSolved: 15,
    successRate: 38,
    lastActive: "2024-01-08T11:20:00Z",
    averageAttempts: 5.2,
    weakAreas: ["For Loops", "Arrays", "Functions"],
    isAtRisk: true,
  },
  {
    id: "5",
    name: "Jessica Taylor",
    email: "jessica@example.com",
    avatar: "/student-avatar.png",
    problemsSolved: 54,
    successRate: 72,
    lastActive: "2024-01-14T13:30:00Z",
    averageAttempts: 2.6,
    weakAreas: ["Recursion", "OOP Basics"],
    isAtRisk: false,
  },
]

export const mockClassAnalytics: ClassAnalytics = {
  totalStudents: 156,
  activeStudents: 142,
  averageProblemsPerStudent: 38,
  averageSuccessRate: 68,
  atRiskStudents: 23,
  totalSubmissions: 8934,
  problemDistribution: {
    easy: 45,
    medium: 38,
    hard: 17,
  },
  weeklyActivity: [
    { day: "Mon", submissions: 234, students: 89 },
    { day: "Tue", submissions: 312, students: 102 },
    { day: "Wed", submissions: 289, students: 95 },
    { day: "Thu", submissions: 267, students: 88 },
    { day: "Fri", submissions: 198, students: 76 },
    { day: "Sat", submissions: 145, students: 54 },
    { day: "Sun", submissions: 167, students: 62 },
  ],
}
